name: Build & Release Android APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Copy to Android static assets
        run: |
          rm -rf mobile/android_app/app/src/main/python/app/static
          mkdir -p mobile/android_app/app/src/main/python/app/static
          cp -r frontend/build/* mobile/android_app/app/src/main/python/app/static/

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Build Android Release APK
        working-directory: mobile/android_app
        run: ./gradlew assembleRelease

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mobile/android_app/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
